import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import "../../public/assets/fonts/ubuntu.css";
import Navbar from "../layout/navbar";
import Footer from "../layout/footer";
import ClientLayout from "../components/ClientLayout.jsx";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning data-scroll-behavior="smooth">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased overflow-x-hidden`}
        suppressHydrationWarning
      >
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
